name: Django CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Set Environment Variables
      run: |
        echo "DJANGO_SETTINGS_MODULE=project1.settings" >> $GITHUB_ENV
        echo "SECRET_KEY=testsecret" >> $GITHUB_ENV
        echo "DEBUG=True" >> $GITHUB_ENV
        echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> $GITHUB_ENV
        echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db" >> $GITHUB_ENV

    - name: Run Migrations
      run: python manage.py migrate

    - name: Run Tests
      run: python manage.py test

    - name: Collect Static Files
      run: python manage.py collectstatic --noinput

    - name: Deploy to Render
      if: success()
      run: |
        curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"